### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ghost** [icflorescu/openshift-cartridge-mongodb#12]
I'm trying to install the cartridge and I get this error: " The cartridge manifest at 'https://github.com/icflorescu/openshift-cartridge-mongodb.git' must be smaller than 20480 bytes"

**Comment by ghost** [comment]
Opps! I'm sorry. Works using this url: "http://cartreflect-claytondev.rhcloud.com/github/icflorescu/openshift-cartridge-mongodb". Thanks.

**Comment by icflorescu** [comment]
Closing, then.
