### ISSUE TITLE
Missing features (for production) 

### ISSUE THREAD

**Issue by alrosot** [icflorescu/openshift-cartridge-mongodb#16]
Hi! Congrats for the great cartridge. 

You are very clear stating that this code is not production ready. Is there any special reason to say that? Some topic that you could use some help? 

Like performance, security, reliability... 

Thanks

**Comment by icflorescu** [comment]
Hi,
Thanks for the kind words!

No special reason, except maybe the fact that you'll have to implement your own backup scenario.
I know of people using it in production with no problems so far (some of them are customers of mine), but the cartridge itself is free software, I make no money out of publishing it, and therefore I take no responsibility for any potential damage or data loss. It's in the standard [ISC License](https://github.com/icflorescu/openshift-cartridge-mongodb/blob/master/LICENSE).

If you know enough about linux and MongoDB to understand what happens in the [install/control scripts](https://github.com/icflorescu/openshift-cartridge-mongodb/tree/master/bin) it's probably safe to use it (and you can even help me improve it – pull-requests are welcome, in the good tradition of open-source :-). If not, or if you're looking for a dedicated, professional alternative, you should have a look at something like [mLab](https://mlab.com/) or [Compose.io](https://compose.io/).

**Comment by alrosot** [comment]
Excellent! 

I'll be happy to eventually contribute to it. But so far I found the cartridge just perfect. 

Thanks again, I'm closing the ticket.
