### ISSUE TITLE
Can't see MONGODB_URL (one app, separate gears) ?

### ISSUE THREAD

**Issue by scriptdealer** [icflorescu/openshift-cartridge-mongodb#20]
I'm sorry if this is stupid, but I'm running official Go cartridge as one gear and this one as second. My first 'Go' gear doesn't see MONGODB_URL environment variable, is this ok ?

If you want to see it for yourself, add these lines to 'hello' function of brand new web.go:

fmt.Fprintln(res, "List of environment variables:")
fmt.Fprintln(res, "------------------------------")
ev := os.Environ()
for _, e := range ev {  fmt.Fprintln(res, e)}

**Comment by icflorescu** [comment]
It's definitely not stupid and not ok :-) I just never got to test it with the Go cartridge so far, and I'm afraid won't have a chance to do it soon. [Here](https://github.com/icflorescu/openshift-cartridge-mongodb/blob/master/hooks/publish-nosql-db-connection-info)'s where the env variables are getting published.

I'll investigate this at some point, but I just don't know when. Meanwhile, feel free to dig around and if you find something, please let me know.

**Comment by scriptdealer** [comment]
No, I'm stupid, really. I mistook gear for cartridge, and after proper re-install it working just fine. Thank you for your job ;] Just a little shame that OpenShift v3 will be using Docker cartridges pretty soon.

**Comment by icflorescu** [comment]
"OpenShift v3 will be using Docker cartridges pretty soon" - yeah, it's a bit frustrating to have all this work made obsolete by Docker cartridges, but hey, it's progress ;-).

Haven't used Docker before, but AFAIK this should be good news, I guess. If OpenShift's implementation will be flexible and "quirks-free", in theory we shouldn't even need things like this cartridge.
