### ISSUE TITLE
Question: Are you able to use Mongodb 3 using this cartridge?

### ISSUE THREAD

**Issue by vikramsoni2** [icflorescu/openshift-cartridge-mongodb#5]

**Comment by icflorescu** [comment]
Current version **is** 3.0.2 and I'll most likely update to 3.0.3 soon.

**Comment by vikramsoni2** [comment]
Great, thanks! Looks like this is a pretty good solution.
Thinking about using this one instead openshift mongodb cartridge. any recommendation / consideration?

Best Regards.

**Comment by icflorescu** [comment]
Nothing besides what's already in the [README](https://github.com/icflorescu/openshift-cartridge-mongodb/blob/master/README.md) :-)
