### ISSUE TITLE
Can't connect to mongodb

### ISSUE THREAD

**Issue by ocorsvall** [icflorescu/openshift-cartridge-mongodb#6]
Hi!

I setup your cartridge on my openshift account by i can't connect to mongodb.
When i check the "MONGODB_URL" environment variable it seems to be set to my public adress:
mongodb://****.rhcloud.com 
Shouldnt this be the local adress to the cartridge as i dont want it to be accessible from outside?

**Comment by icflorescu** [comment]
There was a bug in the install script which led to an incorrect MONGODB_URL **when the cartridge was deployed in the main gear**.

MONGODB_URL only had the correct value when this cartridge was deployed in a **separate** gear, which is actually the most common usage scenario.

Fixed now, anyway. Thanks for noticing.

**Comment by icflorescu** [comment]
Regarding the initial comment, the MongoDB instance **cannot** be accessed from outside, except when using `rhc port-forward` on an authorised machine.
